// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package dbsqlc

import (
	"context"
)

const countIssuesByPriority = `-- name: CountIssuesByPriority :many
SELECT priority, COUNT(*) AS count FROM issues GROUP BY priority
`

type CountIssuesByPriorityRow struct {
	Priority string `json:"priority"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountIssuesByPriority(ctx context.Context) ([]CountIssuesByPriorityRow, error) {
	rows, err := q.db.Query(ctx, countIssuesByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIssuesByPriorityRow{}
	for rows.Next() {
		var i CountIssuesByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total_users FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}
