// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name, owner_user_id, owner_team_id)
VALUES ($1, $2, $3)
RETURNING id, name, owner_user_id, owner_team_id, created_at, updated_at
`

type CreateBoardParams struct {
	Name        string      `json:"name"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	OwnerTeamID pgtype.UUID `json:"owner_team_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.OwnerUserID, arg.OwnerTeamID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, name, owner_user_id, owner_team_id, created_at, updated_at FROM boards WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalBoard = `-- name: GetPersonalBoard :one
SELECT id, name, owner_user_id, owner_team_id, created_at, updated_at FROM boards WHERE owner_user_id = $1
`

func (q *Queries) GetPersonalBoard(ctx context.Context, ownerUserID pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getPersonalBoard, ownerUserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBoard = `-- name: GetTeamBoard :one
SELECT id, name, owner_user_id, owner_team_id, created_at, updated_at FROM boards WHERE owner_team_id = $1
`

func (q *Queries) GetTeamBoard(ctx context.Context, ownerTeamID pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getTeamBoard, ownerTeamID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
