// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board_columns.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBoardColumn = `-- name: CreateBoardColumn :one
INSERT INTO board_columns (board_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, board_id, name, position, created_at
`

type CreateBoardColumnParams struct {
	BoardID  uuid.UUID `json:"board_id"`
	Name     string    `json:"name"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateBoardColumn(ctx context.Context, arg CreateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createBoardColumn, arg.BoardID, arg.Name, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoardColumn = `-- name: DeleteBoardColumn :exec
DELETE FROM board_columns WHERE id = $1
`

func (q *Queries) DeleteBoardColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardColumn, id)
	return err
}

const listBoardColumns = `-- name: ListBoardColumns :many
SELECT id, board_id, name, position, created_at FROM board_columns
WHERE board_id = $1
ORDER BY position
`

func (q *Queries) ListBoardColumns(ctx context.Context, boardID uuid.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listBoardColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBoardColumn = `-- name: ReorderBoardColumn :one
UPDATE board_columns
SET position = $2
WHERE id = $1
RETURNING id, board_id, name, position, created_at
`

type ReorderBoardColumnParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) ReorderBoardColumn(ctx context.Context, arg ReorderBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, reorderBoardColumn, arg.ID, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateBoardColumn = `-- name: UpdateBoardColumn :one
UPDATE board_columns
SET name = $2
WHERE id = $1
RETURNING id, board_id, name, position, created_at
`

type UpdateBoardColumnParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateBoardColumn(ctx context.Context, arg UpdateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateBoardColumn, arg.ID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
