// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const addLabelToIssue = `-- name: AddLabelToIssue :exec
INSERT INTO issue_labels (issue_id, label_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddLabelToIssueParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) AddLabelToIssue(ctx context.Context, arg AddLabelToIssueParams) error {
	_, err := q.db.Exec(ctx, addLabelToIssue, arg.IssueID, arg.LabelID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (name, color)
VALUES ($1, $2)
RETURNING id, name, color, created_at
`

type CreateLabelParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT id, name, color, created_at FROM labels WHERE id = $1
`

func (q *Queries) GetLabelByID(ctx context.Context, id uuid.UUID) (Label, error) {
	row := q.db.QueryRow(ctx, getLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, name, color, created_at FROM labels ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForIssue = `-- name: ListLabelsForIssue :many
SELECT l.id, l.name, l.color, l.created_at
FROM labels l
JOIN issue_labels il ON il.label_id = l.id
WHERE il.issue_id = $1
ORDER BY l.name
`

func (q *Queries) ListLabelsForIssue(ctx context.Context, issueID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabelFromIssue = `-- name: RemoveLabelFromIssue :exec
DELETE FROM issue_labels
WHERE issue_id = $1 AND label_id = $2
`

type RemoveLabelFromIssueParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveLabelFromIssue(ctx context.Context, arg RemoveLabelFromIssueParams) error {
	_, err := q.db.Exec(ctx, removeLabelFromIssue, arg.IssueID, arg.LabelID)
	return err
}
