// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PriorityType string

const (
	PriorityTypeLow      PriorityType = "Low"
	PriorityTypeMedium   PriorityType = "Medium"
	PriorityTypeHigh     PriorityType = "High"
	PriorityTypeCritical PriorityType = "Critical"
)

func (e *PriorityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriorityType(s)
	case string:
		*e = PriorityType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriorityType: %T", src)
	}
	return nil
}

type NullPriorityType struct {
	PriorityType PriorityType `json:"priority_type"`
	Valid        bool         `json:"valid"` // Valid is true if PriorityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriorityType) Scan(value interface{}) error {
	if value == nil {
		ns.PriorityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriorityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriorityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriorityType), nil
}

type TeamRole string

const (
	TeamRoleOwner  TeamRole = "owner"
	TeamRoleAdmin  TeamRole = "admin"
	TeamRoleMember TeamRole = "member"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"team_role"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type Board struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	OwnerTeamID pgtype.UUID        `json:"owner_team_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BoardColumn struct {
	ID        uuid.UUID          `json:"id"`
	BoardID   uuid.UUID          `json:"board_id"`
	Name      string             `json:"name"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	AssigneeID    pgtype.UUID        `json:"assignee_id"`
	TeamID        pgtype.UUID        `json:"team_id"`
	BoardColumnID pgtype.UUID        `json:"board_column_id"`
	Position      int32              `json:"position"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Priority      string             `json:"priority"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IssueLabel struct {
	IssueID uuid.UUID `json:"issue_id"`
	LabelID uuid.UUID `json:"label_id"`
}

type Label struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	AvatarUrl   string             `json:"avatar_url"`
	MaxMembers  int32              `json:"max_members"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	UserID   uuid.UUID          `json:"user_id"`
	TeamID   uuid.UUID          `json:"team_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Permissions  int32              `json:"permissions"`
}
