// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToTeam = `-- name: AddUserToTeam :one
INSERT INTO team_members (user_id, team_id, role)
VALUES ($1, $2, $3)
RETURNING user_id, team_id, role, joined_at
`

type AddUserToTeamParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddUserToTeam(ctx context.Context, arg AddUserToTeamParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addUserToTeam, arg.UserID, arg.TeamID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) AS count
FROM team_members
WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description, created_by, avatar_url, max_members)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, created_by, avatar_url, max_members, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"created_by"`
	AvatarUrl   string    `json:"avatar_url"`
	MaxMembers  int32     `json:"max_members"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.AvatarUrl,
		arg.MaxMembers,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.AvatarUrl,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT t.id, t.name, t.description, t.created_by, t.avatar_url, t.max_members, t.created_at, t.updated_at
FROM teams t
WHERE t.id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.AvatarUrl,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT t.id, t.name, t.description, t.created_by, t.avatar_url, t.max_members, t.created_at, t.updated_at
FROM teams t
WHERE t.name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.AvatarUrl,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.user_id, u.name AS user_name, u.email, tm.role, tm.joined_at
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.joined_at ASC
`

type ListTeamMembersRow struct {
	UserID   uuid.UUID          `json:"user_id"`
	UserName string             `json:"user_name"`
	Email    string             `json:"email"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, t.description, t.created_by, t.avatar_url, t.max_members, t.created_at, t.updated_at
FROM teams t
ORDER BY t.created_at DESC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.AvatarUrl,
			&i.MaxMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.description, tm.role, tm.joined_at, t.created_at, t.updated_at
FROM team_members tm
JOIN teams t ON t.id = tm.team_id
WHERE tm.user_id = $1
ORDER BY tm.joined_at ASC
`

type ListUserTeamsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUserTeams(ctx context.Context, userID uuid.UUID) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTeamsRow{}
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM team_members
WHERE user_id = $1 AND team_id = $2
`

type RemoveUserFromTeamParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTeam, arg.UserID, arg.TeamID)
	return err
}
